// Opt-in billed test: silent synthetic input, isolated memory, temporary output
// sink. No physical microphone, speaker, personal context or desktop actions.
import {spawn,execFileSync} from 'node:child_process';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import assert from 'node:assert/strict';
import OpenAI from 'openai';import {LiveWS} from 'openai/resources/live/ws';
import {loadApiKey} from '../runtime/credentials.mjs';import {Audio} from '../runtime/audio.mjs';import {LiveSession} from '../runtime/live-session.mjs';import {LiveIdle} from '../runtime/live-idle.mjs';import {idleInstruction} from '../runtime/idle.mjs';import {StreamingVoiceEffects} from '../runtime/streaming-voice-effects.mjs';import {Memory} from '../runtime/memory.mjs';
const dir=mkdtempSync(join(tmpdir(),'oma-idle-')),memory=new Memory(join(dir,'memory.sqlite'));const sink='oma_idle_'+process.pid;const module=execFileSync('pactl',['load-module','module-null-sink',`sink_name=${sink}`,'rate=24000','channels=1']).toString().trim();
let clock,interval,tick,timeout,session,idle,closed=false;const prompts=[],captions=[],errors=[];let lastSpoken=0;
const audio=new Audio(level=>{if(level>.04){lastSpoken=performance.now();idle.output()}},e=>errors.push(String(e)),{volume:3,startupBufferMs:250,outputTarget:sink});audio.outputBuffer=new StreamingVoiceEffects({deliver:pcm=>audio.enqueue(pcm),onError:e=>errors.push(e.message)});
try{
 const key=await loadApiKey();session=new LiveSession({config:{model:'gpt-live-1',store:false,instructions:'Speak Japanese. Wait quietly until instructed to speak. Speak each requested notice once. Do not delegate.',audio:{format:{type:'audio/pcm',rate:24000},output:{voice:'cedar'}}},connect:()=>new LiveWS(new OpenAI({apiKey:key}),{reconnect:false}),audio,memory,emit:p=>{if(p.error)errors.push(p.error);if(p.assistantText)captions.push(p.assistantText);if(p.userText)idle.input(p.userText)},execute:async()=>({}),cancelTools(){}});
 idle=new LiveIdle({ready:()=>session.started,speak:bye=>{prompts.push({farewell:bye,atMs:Math.round(performance.now()-clock)});session.instruct(idleInstruction('ja',bye)+' Speak now once.');},dismiss:()=>closed=true});
 await session.start();clock=performance.now();idle.show(true);interval=setInterval(()=>session.appendAudio(Buffer.alloc(960)),20);tick=setInterval(()=>idle.tick(),100);
 await new Promise((resolve,reject)=>{timeout=setTimeout(()=>reject(Error('Idle flow timed out')),55000);const poll=setInterval(()=>{if(closed){clearInterval(poll);resolve()}else if(errors.length){clearInterval(poll);reject(Error(errors.join('; ')))}},100);timeout.unref();setTimeout(()=>clearInterval(poll),56000).unref()});
 assert.equal(prompts.length,2);assert.equal(prompts[0].farewell,false);assert.equal(prompts[1].farewell,true);assert.ok(performance.now()-lastSpoken>=1500);assert.equal(errors.length,0);console.log(JSON.stringify({prompts,closedAtMs:Math.round(performance.now()-clock),finalCaption:captions.at(-1),errors}));
}finally{clearInterval(interval);clearInterval(tick);clearTimeout(timeout);await session?.close();await audio.close();memory.close();execFileSync('pactl',['unload-module',module]);rmSync(dir,{recursive:true,force:true});}
