import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Memory} from '../runtime/memory.mjs';
const provider=await import('../runtime/voice-provider.mjs').catch(()=>({}));
test('local selection survives restart without changing credentials or conversation memory',t=>{
 assert.equal(typeof provider.setVoiceProvider,'function');
 const dir=mkdtempSync(join(tmpdir(),'oma-provider-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));
 let memory=new Memory(join(dir,'memory.sqlite'));
 memory.remember('favorite','blue');memory.add('user','hello');
 assert.equal(provider.voiceProvider(memory),'gpt-live');
 provider.setVoiceProvider(memory,'local');memory.close();
 memory=new Memory(join(dir,'memory.sqlite'));t.after(()=>memory.close());
 assert.equal(provider.voiceProvider(memory),'local');
 assert.equal(memory.search('hello').length,1);assert.equal(memory.facts()[0].value,'blue');
 assert.throws(()=>provider.setVoiceProvider(memory,'cloud-fallback'),/Unknown voice provider/);
 assert.equal(provider.voiceProvider(memory),'local');
 provider.setVoiceProvider(memory,'gpt-live');assert.equal(provider.voiceProvider(memory),'gpt-live');
});
test('switch stops the active conversation before saving and requesting a worker restart',async()=>{
 assert.equal(typeof provider.switchVoiceProvider,'function');
 const events=[],memory={set:(key,value)=>events.push(['save',key,value])};
 await provider.switchVoiceProvider({memory,value:'local',stop:async()=>events.push(['stop']),emit:p=>events.push(p)});
 assert.deepEqual(events[0],['stop']);assert.deepEqual(events[1],['save','voiceProvider','local']);
 assert.equal(events[2].restartWorker,true);assert.equal(events[2].keyConfigured,false);
 await assert.rejects(()=>provider.switchVoiceProvider({memory,value:'invalid',stop:async()=>events.push(['unexpected']),emit(){}}),/Unknown/);
 assert.equal(events.length,3);
});
